apiVersion: backup.example.com/v1alpha1
kind: BackupSchedule
metadata:
  labels:
    app.kubernetes.io/name: autobackup-manifest-operator
    app.kubernetes.io/managed-by: kustomize
  name: backupschedule-sample
spec:
  # TODO(user): Add fields here
